<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class OrderSeeder extends Seeder
{
    public function run()
    {
        DB::table('orders')->insert([
            [
                'user_id' => 1,
                'code' => 'ORD001',
                'recipient_name' => 'Nguyen Van A',
                'recipient_phone' => '0912345678',
                'shipping_address' => '123 Đường ABC, Quận 1, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 500000,
                'payment_method' => 'Bank_transfer',
                'payment_status' => 'Pending',
                'status' => 'Pending',
                'user_note' => 'Giao hàng nhanh giúp mình',
                'admin_note' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 2,
                'code' => 'ORD002',
                'recipient_name' => 'Tran Thi B',
                'recipient_phone' => '0987654321',
                'shipping_address' => '456 Đường XYZ, Quận 2, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 1500000,
                'payment_method' => 'Momo',
                'payment_status' => 'Completed',
                'status' => 'Completed',
                'user_note' => null,
                'admin_note' => 'Đã giao thành công',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 3,
                'code' => 'ORD003',
                'recipient_name' => 'Le Van C',
                'recipient_phone' => '0901122334',
                'shipping_address' => '789 Đường DEF, Quận 3, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 250000,
                'payment_method' => 'cod',
                'payment_status' => 'Pending',
                'status' => 'Confirm',
                'user_note' => 'Có thể giao sau 18h',
                'admin_note' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 4,
                'code' => 'ORD004',
                'recipient_name' => 'Pham Thi D',
                'recipient_phone' => '0965234789',
                'shipping_address' => '101 Đường GHI, Quận 4, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 800000,
                'payment_method' => 'Bank_transfer',
                'payment_status' => 'Failed',
                'status' => 'Cancelled',
                'user_note' => null,
                'admin_note' => 'Khách huỷ đơn',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 5,
                'code' => 'ORD005',
                'recipient_name' => 'Hoang Van E',
                'recipient_phone' => '0933567890',
                'shipping_address' => '202 Đường JKL, Quận 5, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 1200000,
                'payment_method' => 'Momo',
                'payment_status' => 'Completed',
                'status' => 'Delivering',
                'user_note' => 'Nhớ gọi trước khi giao',
                'admin_note' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 6,
                'code' => 'ORD006',
                'recipient_name' => 'Vu Thi F',
                'recipient_phone' => '0921345678',
                'shipping_address' => '303 Đường MNO, Quận 6, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 950000,
                'payment_method' => 'cod',
                'payment_status' => 'Pending',
                'status' => 'Edited',
                'user_note' => null,
                'admin_note' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 7,
                'code' => 'ORD007',
                'recipient_name' => 'Do Van G',
                'recipient_phone' => '0975642310',
                'shipping_address' => '404 Đường PQR, Quận 7, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 2200000,
                'payment_method' => 'Bank_transfer',
                'payment_status' => 'Completed',
                'status' => 'Pending',
                'user_note' => null,
                'admin_note' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 8,
                'code' => 'ORD008',
                'recipient_name' => 'Bui Thi H',
                'recipient_phone' => '0985234123',
                'shipping_address' => '505 Đường STU, Quận 8, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 1750000,
                'payment_method' => 'Momo',
                'payment_status' => 'Refunded',
                'status' => 'Cancelled',
                'user_note' => 'Đơn hàng bị lỗi',
                'admin_note' => 'Hoàn tiền cho khách',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 9,
                'code' => 'ORD009',
                'recipient_name' => 'Nguyen Van K',
                'recipient_phone' => '0913344556',
                'shipping_address' => '606 Đường VWX, Quận 9, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 670000,
                'payment_method' => 'cod',
                'payment_status' => 'Pending',
                'status' => 'Confirm',
                'user_note' => null,
                'admin_note' => null,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 10,
                'code' => 'ORD010',
                'recipient_name' => 'Tran Thi M',
                'recipient_phone' => '0909876543',
                'shipping_address' => '707 Đường YZA, Quận 10, TP.HCM',
                'order_date' => Carbon::now(),
                'total_price' => 1950000,
                'payment_method' => 'Bank_transfer',
                'payment_status' => 'Completed',
                'status' => 'Completed',
                'user_note' => 'Cảm ơn shop',
                'admin_note' => 'Đã giao thành công',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
